feat: enable versioning by default
makeswift/makeswift pull request #648
Opened 2024-01-11 13:15 UTC by fikrikarim

2024-01-11 16:42 UTC, alexhwoods commented
It seems I'm still able to pass the `siteVersions` parameter to the API handler config, although it isn't having any effect.

 Could we make this a type error?

```import { MakeswiftApiHandler } from '@makeswift/runtime/next'

export default MakeswiftApiHandler(process.env.MAKESWIFT_SITE_API_KEY!, {
  appOrigin: process.env.MAKESWIFT_APP_ORIGIN,
  apiOrigin: process.env.MAKESWIFT_API_ORIGIN,
  siteVersions: false,
})
```

2024-01-11 16:50 UTC, fikrikarim commented
> It seems I'm still able to pass the `siteVersions` parameter to the API handler config, although it isn't having any effect.
> 
> Could we make this a type error?
> 
> ```
> 
> export default MakeswiftApiHandler(process.env.MAKESWIFT_SITE_API_KEY!, {
>   appOrigin: process.env.MAKESWIFT_APP_ORIGIN,
>   apiOrigin: process.env.MAKESWIFT_API_ORIGIN,
>   siteVersions: false,
> })
> ```

Oh yeah thanks for catching that. I removed the type from manifest but I forgot to remove it from the API handler. Thanks!

2024-01-11 16:50 UTC, alexhwoods commented
> > It seems I'm still able to pass the `siteVersions` parameter to the API handler config, although it isn't having any effect.
> > Could we make this a type error?
> > ```
> > 
> > export default MakeswiftApiHandler(process.env.MAKESWIFT_SITE_API_KEY!, {
> >   appOrigin: process.env.MAKESWIFT_APP_ORIGIN,
> >   apiOrigin: process.env.MAKESWIFT_API_ORIGIN,
> >   siteVersions: false,
> > })
> > ```
> 
> Oh yeah thanks for catching that. I removed the type from manifest but I forgot to remove it from the API handler. Thanks!

alright, confirmed fixed!
![CleanShot 2024-01-11 at 11 50 02](https://github.com/makeswift/makeswift/assets/7907782/94d90cf4-1e1d-4c4e-9d29-79c94af27442)

2024-01-11 21:01 UTC, alexhwoods approved these changes

2024-01-11 21:15 UTC, migueloller requested changes
Looks good. Just have 1 request to fix the behavior of `getServerSideProps`

2024-01-11 21:15 UTC, migueloller commented on packages/runtime/src/next/index.tsx
> +  })
This needs to be hardcoded to `MakeswiftSiteVersion.Working` to preserve its behavior.

2024-01-11 21:22 UTC, migueloller approved these changes
LGTM!

2024-01-11 21:26 UTC, migueloller commented
> Thoughts about this MR:
> 
> 1. Should we make make `siteVersion` parameter optional on public methods `getPage()` and `getPages()`?

We could make it optional but it feels better to make them required so that it's harder to make a mistake

> 2. Should we make the `siteVersion` parameter an object parameter like this?
> 
> ```ts
> async getGlobalElement(id, { siteVersion })
> ```

I would prefer named parameter like this, yes, but it seems that they ended up being positional parameters.

> 3. I think for "internal methods" like `getSwatch`, we need to make the `siteVersion` required, because otherwise we will forget to pass the `siteVersion` when we use it internally. But for external API, I'm making those optional for now, not sure which one is better here.

Yes! For the same reasons we can make the external API required.

> 4. On that note, it's so weird to have a Makeswift client, but we expose our "internal methods" like `getSwatch`. In the future, it might be better to separate Makeswift client that users will use, and a Makeswift client that we use internally.

I think in the future we're wanting to expose all these things as part of our public API. But in the mean time, yeah, might make sense to have separate private and public clients.

2024-01-11 21:26 UTC, migueloller commented
> It seems I'm still able to pass the `siteVersions` parameter to the API handler config, although it isn't having any effect.
> 
> Could we make this a type error?
> 
> ```
> 
> export default MakeswiftApiHandler(process.env.MAKESWIFT_SITE_API_KEY!, {
>   appOrigin: process.env.MAKESWIFT_APP_ORIGIN,
>   apiOrigin: process.env.MAKESWIFT_API_ORIGIN,
>   siteVersions: false,
> })
> ```

We could do that by doing `siteVersions?: never`

2024-01-11 21:31 UTC, merged

2024-01-12 07:14 UTC, fikrikarim commented
> I would prefer named parameter like this, yes, but it seems that they ended up being positional parameters.

During my first iteration, I actually used a named parameter. But I found it weird to mix a  required named parameter together with a required positional parameter like this:
```
async getGlobalElement(id, { siteVersion })
```

It's a different story if the named parameter is an optional parameter like `connection`. But we can always change this later.